# Generated by Django 5.1.6 on 2025-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_generatorconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorconfiguration',
            name='database_type',
            field=models.IntegerField(choices=[(1, 'PostgreSQL'), (2, 'MongoDB')], default=1, help_text='Select the type of database.'),
        ),
    ]
